package com.app.policy;

public enum Action {
    MANAGE_PERMISSIONS,
    MANAGE_CHANNELS,
    MANAGE_ROLES,
    MANAGE_GUILDS,
    MANAGE_USERS,
    MANAGE_EMOJIS,
    MANAGE_MESSAGE,
    MANAGE_NICKNAMES,
    MANAGE_VOICE_STATES,
    MANAGE_INVITES,
    BAN,
    JOIN_CHANNEL, SEND_MESSAGE
}
