CREATE SEQUENCE IF NOT EXISTS member_overrides_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS role_overrides_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE bans
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    guild_id   VARCHAR(255)                            NOT NULL,
    user_id    VARCHAR(255)                            NOT NULL,
    banned_by  VARCHAR(255)                            NOT NULL,
    reason     VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_bans PRIMARY KEY (id)
);

ALTER TABLE users
    ADD COLUMN role VARCHAR(50);
CREATE TABLE channels
(
    id       BIGINT       NOT NULL,
    name     VARCHAR(255) NOT NULL,
    guild_id BIGINT       NOT NULL,
    CONSTRAINT pk_channels PRIMARY KEY (id)
);

CREATE TABLE guilds
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    guild_name    VARCHAR(100)                            NOT NULL,
    description   VARCHAR(500),
    guild_icon    VARCHAR(255),
    guild_banner  VARCHAR(255),
    owner_id      BIGINT                                  NOT NULL,
    is_public     BOOLEAN,
    invite_only   BOOLEAN,
    member_count  INTEGER,
    channel_count INTEGER,
    deleted       BOOLEAN,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_guilds PRIMARY KEY (id)
);

ALTER TABLE guilds
    ADD CONSTRAINT fk_guild_owner
        FOREIGN KEY (owner_id)
            REFERENCES users(id);

CREATE TABLE member_overrides
(
    id                  BIGINT NOT NULL,
    channel_id          BIGINT,
    member_id           BIGINT,
    base_perms          BIGINT,
    allowed_permissions BIGINT,
    denied_permissions  BIGINT,
    CONSTRAINT pk_member_overrides PRIMARY KEY (id)
);

CREATE TABLE member_roles
(
    member_id BIGINT NOT NULL,
    role_id   BIGINT NOT NULL
);

CREATE TABLE members
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username       VARCHAR(100),
    nickname       VARCHAR(100),
    avatar         VARCHAR(255),
    owner          BOOLEAN                                 NOT NULL,
    muted          BOOLEAN                                 NOT NULL,
    banned         BOOLEAN                                 NOT NULL,
    joined_at      TIMESTAMP WITHOUT TIME ZONE,
    last_active_at TIMESTAMP WITHOUT TIME ZONE,
    user_id        BIGINT                                  NOT NULL,
    guild_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_members PRIMARY KEY (id)
);

CREATE TABLE message
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(255),
    guild_id   BIGINT,
    channel_id BIGINT,
    sender_id  BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

CREATE TABLE role_overrides
(
    id         BIGINT NOT NULL,
    channel_id BIGINT,
    role_id    BIGINT,
    allow      BIGINT,
    deny       BIGINT,
    CONSTRAINT pk_role_overrides PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    permissions BIGINT                                  NOT NULL,
    position    INTEGER                                 NOT NULL,
    color       VARCHAR(255),
    mentionable BOOLEAN                                 NOT NULL,
    hoisted     BOOLEAN                                 NOT NULL,
    guild_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_sessions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    VARCHAR(255)                            NOT NULL,
    session_id VARCHAR(255)                            NOT NULL,
    active     BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_sessions PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id     UUID                                    NOT NULL,
    username      VARCHAR(32)                             NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_684af0c423c1cf8988897ae01 UNIQUE (guild_id, name);

ALTER TABLE members
    ADD CONSTRAINT uc_c996b9d4e861a9049e8525f8d UNIQUE (guild_id, user_id);

ALTER TABLE user_sessions
    ADD CONSTRAINT uc_user_sessions_sessionid UNIQUE (session_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_public UNIQUE (public_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE INDEX idx_guild_name ON guilds (guild_name);

CREATE INDEX idx_member_guild_banned ON members (guild_id, banned);

CREATE INDEX idx_member_guild_user ON members (guild_id, user_id);

CREATE INDEX idx_owner_id ON guilds (owner_id);

ALTER TABLE channels
    ADD CONSTRAINT FK_CHANNELS_ON_GUILD FOREIGN KEY (guild_id) REFERENCES guilds (id);

ALTER TABLE members
    ADD CONSTRAINT FK_MEMBERS_ON_GUILD FOREIGN KEY (guild_id) REFERENCES guilds (id);

CREATE INDEX idx_member_guild ON members (guild_id);

ALTER TABLE members
    ADD CONSTRAINT FK_MEMBERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_member_user ON members (user_id);

ALTER TABLE member_overrides
    ADD CONSTRAINT FK_MEMBER_OVERRIDES_ON_CHANNEL FOREIGN KEY (channel_id) REFERENCES channels (id);

ALTER TABLE member_overrides
    ADD CONSTRAINT FK_MEMBER_OVERRIDES_ON_MEMBER FOREIGN KEY (member_id) REFERENCES members (id);

ALTER TABLE roles
    ADD CONSTRAINT FK_ROLES_ON_GUILD FOREIGN KEY (guild_id) REFERENCES guilds (id);

ALTER TABLE role_overrides
    ADD CONSTRAINT FK_ROLE_OVERRIDES_ON_CHANNEL FOREIGN KEY (channel_id) REFERENCES channels (id);

ALTER TABLE role_overrides
    ADD CONSTRAINT FK_ROLE_OVERRIDES_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE member_roles
    ADD CONSTRAINT fk_memrol_on_member_entity FOREIGN KEY (member_id) REFERENCES members (id);

ALTER TABLE member_roles
    ADD CONSTRAINT fk_memrol_on_role_entity FOREIGN KEY (role_id) REFERENCES roles (id);